name: update

on:
  push:
    branches:
      - main
    schedule:
      cron: '0 6 * * 1'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: get branch
      uses: actions/checkout@main
      with:
        fetch-depth: 1
      - name: run script
      run: |
        cd ${GITHUB_WORKSPACE}/update
        go run main.go
      - name: deploy
      run: |
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git add . 
        git commit -m "Dynamic README update ✨"
        git push --all -f https://${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git